name: Build and publish to GitHub Packages

on:
  push:
    branches:
    - master
  release:
    types:
    - published

jobs:
  build:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to GitHub Packages (latest)
      uses: docker/build-push-action@v1
      with:
        add_git_labels: true
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/gw2-dps-report
        tags: latest
        username: ${{ github.actor }}
      if: "!contains(github.ref, 'refs/tags/v')"
    - name: Tag
      run: |
        echo "::set-env name=IMAGE_TAG::$(echo ${{ github.ref }} | sed -e 's/^refs\/tags\/v//g')"
      if: "contains(github.ref, 'refs/tags/v')"
    - name: Publish to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        add_git_labels: true
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/gw2-dps-report
        tags: ${{ env.IMAGE_TAG }}
        username: ${{ github.actor }}
      if: "contains(github.ref, 'refs/tags/v')"
